<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.3">
  <POU Name="_csp_case_transport_highest" Id="{c81e8c71-05c1-45e7-b98b-fabcd3fb8245}" SpecialFunc="None">
    <Declaration><![CDATA[(*********************************** G.D S.p.A. - Technical Department ***********************************
============= PROGRAM INFO ============
FOLDER:             TBD
MACHINES INVOLVED:  TBD 

============= DESCRIPTION =============
csp main interface program

============= REVISIONS ===============
Date		Version	 	Author      	Description             
----------	-------		------------  	--------------------------------------------
2019/09/27 	0000.00	 	M.Grasso		Creation of the PRG

**********************************************************************************************************)
PROGRAM _csp_case_transport_highest
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[csp_case_transport();
csp_case_transport_virtualMaster();

(* CSP *)
	(* TRANSPORT *)
		(* LS *)
		csp_case_transport_ls();
		(* OS *)
		csp_case_transport_os();
		
(* CSP *)
(* TRANSPORT *)
	(* LS *)
	csp_case_transport_ls_leading();
	csp_case_transport_ls_trailing();
	(* OS *)
	csp_case_transport_os_leading();
	csp_case_transport_os_trailing();
	(* TENSIONER *)
	;]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>