<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.3">
  <POU Name="_csp_case_transport_low" Id="{19b1b664-3aab-4218-813d-221e1d398e8a}" SpecialFunc="None">
    <Declaration><![CDATA[(*********************************** G.D S.p.A. - Technical Department ***********************************
============= PROGRAM INFO ============
FOLDER:             TBD
MACHINES INVOLVED:  TBD 

============= DESCRIPTION =============
csp main interface program

============= REVISIONS ===============
Date		Version	 	Author      	Description             
----------	-------		------------  	--------------------------------------------
2019/09/27 	0000.00	 	M.Grasso		Creation of the PRG

**********************************************************************************************************)
PROGRAM _csp_case_transport_low
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[(* CSP *)
	(* TRANSPORT *)
		(* ACC-U-CHANGE *)
		csp_case_transport_accU_depth();
		csp_case_transport_accU_virtualMaster();
		(* LS *)
		(* OS *)
		csp_case_transport_os_minorPlow();
		(* TENSIONER *)
		;]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>