<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.12">
  <POU Name="jog_manager_get_jog_activation_condition" Id="{262d18cd-28fc-4b6a-babe-153701acee53}" SpecialFunc="None">
    <Declaration><![CDATA[(*$
	Returns <i>jog_activation_condition</i> of the instance <b><i>this</i></b>.
$*)
FUNCTION jog_manager_get_jog_activation_condition : BOOL
VAR_IN_OUT
    CONVERSION_this:	jog_manager;	(*$ Instance to which the method applies $*)
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[jog_manager_get_jog_activation_condition := CONVERSION_this.jog_activation_condition;]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>