<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.12">
  <POU Name="jog_manager_is_jog_ready" Id="{c8680cba-df52-475a-b4c9-18fd03918d96}" SpecialFunc="None">
    <Declaration><![CDATA[(*$
	Returns <i>TRUE</i> if the status of the instance <b><i>this</i></b> is
	<a href="#jog_manager_status_enum"><i>JOG_MANAGER_STATUS_READY</i></a>, 
	<i>FALSE</i> otherwise.
$*)
FUNCTION jog_manager_is_jog_ready : BOOL
VAR_IN_OUT
    CONVERSION_this:	jog_manager;	(*$ Instance to which the method applies $*)
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[jog_manager_is_jog_ready := (CONVERSION_this.status = JOG_MANAGER_STATUS_READY);]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>