<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.12">
  <POU Name="jog_manager_is_jog_active" Id="{9e73550c-d55e-469a-b651-be2e2f4453df}" SpecialFunc="None">
    <Declaration><![CDATA[(*$
	Returns <i>TRUE</i> if the status of the instance <b><i>this</i></b> is
	<a href="#jog_manager_status_enum"><i>JOG_MANAGER_STATUS_ACTIVE</i></a>, 
	<i>FALSE</i> otherwise.
$*)
FUNCTION jog_manager_is_jog_active : BOOL
VAR_IN_OUT
    CONVERSION_this:	jog_manager;	(*$ Instance to which the method applies $*)
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[jog_manager_is_jog_active := (CONVERSION_this.status >= JOG_MANAGER_STATUS_ACTIVE);]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>