<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.9">
  <POU Name="_csp_transfer_upstacker_low" Id="{8183ced4-c691-40b8-903f-8eba41e82476}" SpecialFunc="None">
    <Declaration><![CDATA[(*********************************** G.D S.p.A. - Technical Department ***********************************
============= PROGRAM INFO ============
FOLDER:             TBD
MACHINES INVOLVED:  TBD 

============= DESCRIPTION =============
csp main interface program

============= REVISIONS ===============
Date		Version	 	Author      	Description             
----------	-------		------------  	--------------------------------------------
2019/09/27 	0000.00	 	M.Grasso		Creation of the PRG

**********************************************************************************************************)
PROGRAM _csp_transfer_upstacker_low
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[(* TRANSFER *)
	(* UPSTACKER *)
		(* BACKSTOP *)
		;
		(* BELT *)
		;
		(* DOWNSTREAM *)
		;
		(* SENSORS *)
		;
		(* UPSTREAM *)
		;]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>