<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.12">
  <POU Name="_csp_transfer_upstacker_lowest" Id="{4f7c3d0e-c0c6-4450-84bf-2a032beff6c8}" SpecialFunc="None">
    <Declaration><![CDATA[(*********************************** G.D S.p.A. - Technical Department ***********************************
============= PROGRAM INFO ============
FOLDER:             TBD
MACHINES INVOLVED:  TBD 

============= DESCRIPTION =============
csp main interface program

============= REVISIONS ===============
Date		Version	 	Author      	Description             
----------	-------		------------  	--------------------------------------------
2019/09/27 	0000.00	 	M.Grasso		Creation of the PRG

**********************************************************************************************************)
PROGRAM _csp_transfer_upstacker_lowest
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[(*MAIN*)

	(*Brand*)
	
	(*Drives*)
	
	(*Motorization*)
	
	(*Cam Manager*)
	
	(*Services*)
	
	(*Interface*)
	
	(*Safety*)
	;]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>