<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.3">
  <POU Name="_csp_case_glue_normal" Id="{651e871d-4514-4a71-b407-4a6cdb3db3e4}" SpecialFunc="None">
    <Declaration><![CDATA[(*********************************** G.D S.p.A. - Technical Department ***********************************
============= PROGRAM INFO ============
FOLDER:             TBD
MACHINES INVOLVED:  TBD 

============= DESCRIPTION =============
csp main interface program

============= REVISIONS ===============
Date		Version	 	Author      	Description             
----------	-------		------------  	--------------------------------------------
2019/09/27 	0000.00	 	M.Grasso		Creation of the PRG

**********************************************************************************************************)
PROGRAM _csp_case_glue_normal
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[(* CASE *)
	(* GLUE *)
		(* LS *)
		csp_case_glue_ls();
		(* OS *)
		csp_case_glue_os();
		(* SENSORS *)
		csp_case_glue_hotMelt_safety();]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>