<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.3">
  <POU Name="_csp_case_normal" Id="{213976eb-f7c4-42d6-9c4b-f6c14f1b12f2}" SpecialFunc="None">
    <Declaration><![CDATA[(*********************************** G.D S.p.A. - Technical Department ***********************************
============= PROGRAM INFO ============
FOLDER:             TBD
MACHINES INVOLVED:  TBD 

============= DESCRIPTION =============
csp main interface program

============= REVISIONS ===============
Date		Version	 	Author      	Description             
----------	-------		------------  	--------------------------------------------
2019/09/27 	0000.00	 	M.Grasso		Creation of the PRG

**********************************************************************************************************)
PROGRAM _csp_case_normal
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[csp_case();

_csp_case_closing_normal();

_csp_case_discharge_normal();

_csp_case_feed_normal();

_csp_case_flapControl_normal();

_csp_case_glue_normal();

_csp_case_loader_normal();

_csp_case_openFlap_normal();

_csp_case_main_normal();

_csp_case_topRail_normal();

_csp_case_transport_normal();

]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>