<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.12">
  <POU Name="_csp_transfer_low" Id="{d5efe82f-d795-4dc0-b865-c337030c673e}" SpecialFunc="None">
    <Declaration><![CDATA[(*********************************** G.D S.p.A. - Technical Department ***********************************
============= PROGRAM INFO ============
FOLDER:             TBD
MACHINES INVOLVED:  TBD 

============= DESCRIPTION =============
csp main interface program

============= REVISIONS ===============
Date		Version	 	Author      	Description             
----------	-------		------------  	--------------------------------------------
2019/09/27 	0000.00	 	M.Grasso		Creation of the PRG

**********************************************************************************************************)
PROGRAM _csp_transfer_low
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[_csp_transfer_accumulator_low();

_csp_transfer_crosspusher_low();

_csp_transfer_main_low();

_csp_transfer_infeed_low();

_csp_transfer_upstacker_low();]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>