<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.3">
  <POU Name="_csp_case_feed_normal" Id="{55832d7d-2ff2-44f3-a680-f1d387b74ac3}" SpecialFunc="None">
    <Declaration><![CDATA[(*********************************** G.D S.p.A. - Technical Department ***********************************
============= PROGRAM INFO ============
FOLDER:             TBD
MACHINES INVOLVED:  TBD 

============= DESCRIPTION =============
csp main interface program

============= REVISIONS ===============
Date		Version	 	Author      	Description             
----------	-------		------------  	--------------------------------------------
2019/09/27 	0000.00	 	M.Grasso		Creation of the PRG

**********************************************************************************************************)
PROGRAM _csp_case_feed_normal
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[(* CASE *)
	(* FEED *)
		(* ACCU-U-CHANGE*)
		csp_case_feed_magazine_accU();
		csp_case_feed_shuttle_accU();
		csp_case_feed_reject_accU();
		(* ARM *)
		csp_case_feed_arm();
		(* MAGAZINE *)
		csp_case_feed_magazine();
		(* REJECT *)
		csp_case_feed_reject();
		(* SHUTTLE *)
		csp_case_feed_shuttle();

		(*csp_case_feed_kinematic(); Moved to low task to manage all the axis (MCS and ACS) in the same task!

		csp_case_feed_virtualMaster();*)
		
]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>