<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.3">
  <POU Name="_csp_case_main_normal" Id="{a2a6029b-159a-4d56-9110-87e786eef976}" SpecialFunc="None">
    <Declaration><![CDATA[(*********************************** G.D S.p.A. - Technical Department ***********************************
============= PROGRAM INFO ============
FOLDER:             TBD
MACHINES INVOLVED:  TBD 

============= DESCRIPTION =============
csp main interface program

============= REVISIONS ===============
Date		Version	 	Author      	Description             
----------	-------		------------  	--------------------------------------------
2019/09/27 	0000.00	 	M.Grasso		Creation of the PRG

**********************************************************************************************************)
PROGRAM _csp_case_main_normal
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[(* MAIN *)

	(*Brand*)
	
	(*Drives*)
	csp_case_main_drives();
	(*Motorization*)

	(*Cam Manager*)
	
	(*Services*)
	csp_case_main_services();
	csp_case_main_services_airPressure();
		csp_case_main_services_vacuum();
		csp_case_main_services_pushbuttons();
		csp_case_main_services_hotMelt();
		csp_case_main_services_breakers();
		//csp_case_main_ioLink();

	(*Interface*)
	
	(*Safety*)
	]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>