<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.12">
  <POU Name="_csp_case_main_lowest" Id="{f62293a2-88a4-4bbb-b7dd-46af8809c76f}" SpecialFunc="None">
    <Declaration><![CDATA[(*********************************** G.D S.p.A. - Technical Department ***********************************
============= PROGRAM INFO ============
FOLDER:             TBD
MACHINES INVOLVED:  TBD 

============= DESCRIPTION =============
csp main interface program

============= REVISIONS ===============
Date		Version	 	Author      	Description             
----------	-------		------------  	--------------------------------------------
2019/09/27 	0000.00	 	M.Grasso		Creation of the PRG

**********************************************************************************************************)
PROGRAM _csp_case_main_lowest
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[(*MAIN*)

	(*Brand*)
	
	(*Drives*)
	
	(*Motorization*)
	
	(*Cam Manager*)
	
	(*Services*)
	
	(*Interface*)
	
	(*Safety*)
	
	(* Cabinet *)
	csp_case_main_cabinet()
	;]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>