<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.3">
  <POU Name="_csp_main_normal" Id="{a88fa636-1016-4694-a908-fe0dc090faf2}" SpecialFunc="None">
    <Declaration><![CDATA[(*********************************** G.D S.p.A. - Technical Department ***********************************
============= PROGRAM INFO ============
FOLDER:             TBD
MACHINES INVOLVED:  TBD 

============= DESCRIPTION =============
csp main interface program

============= REVISIONS ===============
Date		Version	 	Author      	Description             
----------	-------		------------  	--------------------------------------------
2019/09/27 	0000.00	 	M.Grasso		Creation of the PRG

**********************************************************************************************************)
PROGRAM _csp_main_normal
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[(*MAIN*)

	(* ACC-U-CHANGE *)
	csp_main_accuChange();
	
	(*Drives*)
	
	(*Motorization*)
	csp_main_motorization_speedBalance();
	(*Cam Manager*)
	
		(* PHASE MANAGER *)
		csp_main_phaseManager();
		csp_main_phaseManager_startJob();
		//csp_main_phaseManager_near_end_run();
		//csp_main_phaseManager_run_out();
		csp_main_phaseManager_end_job();
	(*Services*)
	csp_main_services();
	csp_main_services_towerLamp();
	csp_main_services_pushbuttons();
			
	(*Interface*)
	
	
	(*Safety*)
	csp_main_safety();
	csp_main_safety_interface();
	csp_main_safety_connectionShutDown();]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>