<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.3">
  <POU Name="_csp_main_highest" Id="{4a048748-4647-489b-aed1-8aa6c612be1f}" SpecialFunc="None">
    <Declaration><![CDATA[(*********************************** G.D S.p.A. - Technical Department ***********************************
============= PROGRAM INFO ============
FOLDER:             TBD
MACHINES INVOLVED:  TBD 

============= DESCRIPTION =============
csp main interface program

============= REVISIONS ===============
Date		Version	 	Author      	Description             
----------	-------		------------  	--------------------------------------------
2019/09/27 	0000.00	 	M.Grasso		Creation of the PRG

**********************************************************************************************************)
PROGRAM _csp_main_highest
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[(*MAIN*)
 IF	objects_running()  (*//Nick*)
THEN
	quality_checks_cycle();
END_IF;

	(*Drives*)
	csp_main_drives();
	(*Motorization*)
	csp_main_motorization_manager();
	//csp_main_motorization();	
	csp_main_motorization_virtualManager();

	(*Services*)
	
	(*Interface*)
	csp_main_interface();
	csp_main_interface_upstream();
	csp_main_interface_downstream();
	(*Safety*)]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>