<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.3">
  <POU Name="_csp_transfer_infeed_normal" Id="{bf880918-f7a0-4d91-9cc5-e3ba31917124}" SpecialFunc="None">
    <Declaration><![CDATA[(*********************************** G.D S.p.A. - Technical Department ***********************************
============= PROGRAM INFO ============
FOLDER:             TBD
MACHINES INVOLVED:  TBD 

============= DESCRIPTION =============
csp main interface program

============= REVISIONS ===============
Date		Version	 	Author      	Description             
----------	-------		------------  	--------------------------------------------
2019/09/27 	0000.00	 	M.Grasso		Creation of the PRG

**********************************************************************************************************)
PROGRAM _csp_transfer_infeed_normal
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[;
			]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>