<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.12">
  <POU Name="analog_actuator_is_not_initialized" Id="{20d4c11e-b3e6-48b0-acd8-0d716eedce08}" SpecialFunc="None">
    <Declaration><![CDATA[(* Function that returns if an object is not initialized. *)
FUNCTION analog_actuator_is_not_initialized : BOOL
VAR_IN_OUT
	CONVERSION_this:	analog_actuator;	(* object reference *)
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[analog_actuator_is_not_initialized:=NOT CONVERSION_this.CONVERSION_private.initialized;]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>