<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.3">
  <POU Name="_csp_case_closing_low" Id="{c7e41079-db6f-4398-ac6b-336cdae9f33a}" SpecialFunc="None">
    <Declaration><![CDATA[(*********************************** G.D S.p.A. - Technical Department ***********************************
============= PROGRAM INFO ============
FOLDER:             TBD
MACHINES INVOLVED:  TBD 

============= DESCRIPTION =============
csp main interface program

============= REVISIONS ===============
Date		Version	 	Author      	Description             
----------	-------		------------  	--------------------------------------------
2019/09/27 	0000.00	 	M.Grasso		Creation of the PRG

**********************************************************************************************************)
PROGRAM _csp_case_closing_low
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[(* CASE *)
	(* CLOSING *)
		(* OS *)
	
		(* LS *)]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>