<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.12">
  <POU Name="_csp_case_closing_normal" Id="{701a2a2d-ecec-41bb-a331-a3bb5823b6a8}" SpecialFunc="None">
    <Declaration><![CDATA[(*********************************** G.D S.p.A. - Technical Department ***********************************
============= PROGRAM INFO ============
FOLDER:             TBD
MACHINES INVOLVED:  TBD 

============= DESCRIPTION =============
csp main interface program

============= REVISIONS ===============
Date		Version	 	Author      	Description             
----------	-------		------------  	--------------------------------------------
2019/09/27 	0000.00	 	M.Grasso		Creation of the PRG

**********************************************************************************************************)
PROGRAM _csp_case_closing_normal
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[(* CASE *)
	(* CLOSING *)
		(* OS *)
		csp_case_closing_os();
	
		(* LS *)
		csp_case_closing_ls();
		
	]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>