<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.12">
  <POU Name="_csp_case_flapControl_normal" Id="{2960ad6d-e596-4c9a-b58f-67068e3c784e}" SpecialFunc="None">
    <Declaration><![CDATA[(*********************************** G.D S.p.A. - Technical Department ***********************************
============= PROGRAM INFO ============
FOLDER:             TBD
MACHINES INVOLVED:  TBD 

============= DESCRIPTION =============
csp main interface program

============= REVISIONS ===============
Date		Version	 	Author      	Description             
----------	-------		------------  	--------------------------------------------
2019/09/27 	0000.00	 	M.Grasso		Creation of the PRG

**********************************************************************************************************)
PROGRAM _csp_case_flapControl_normal
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[(* CASE *)
	(* FLAP CONTROL *)
		(* BACKSTOP *)
		csp_case_flapControl_backStop();
		(* LS *)
		csp_case_flapControl_ls();
		(* OS *)
		csp_case_flapControl_os();
	



]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>