<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.12">
  <POU Name="_csp_case_discharge_highest" Id="{c50c9d7a-9945-4215-9c93-2042914cf1db}" SpecialFunc="None">
    <Declaration><![CDATA[(*********************************** G.D S.p.A. - Technical Department ***********************************
============= PROGRAM INFO ============
FOLDER:             TBD
MACHINES INVOLVED:  TBD 

============= DESCRIPTION =============
csp main interface program

============= REVISIONS ===============
Date		Version	 	Author      	Description             
----------	-------		------------  	--------------------------------------------
2019/09/27 	0000.00	 	M.Grasso		Creation of the PRG

**********************************************************************************************************)
PROGRAM _csp_case_discharge_highest
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[csp_case_discharge();]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>