<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.3">
  <POU Name="_csp_lowest" Id="{75d7955c-2609-4729-b34f-5f42cf0e58e3}" SpecialFunc="None">
    <Declaration><![CDATA[(*********************************** G.D S.p.A. - Technical Department ***********************************
============= PROGRAM INFO ============
FOLDER:             TBD
MACHINES INVOLVED:  TBD 

============= DESCRIPTION =============
CSP: lowest task

============= REVISIONS ===============
Date		Version	 	Author      	Description             
----------	-------		------------  	--------------------------------------------
2019/04/05 	0000.00	 	G.Cera 			Creation of the PRG

**********************************************************************************************************)

PROGRAM _csp_lowest
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[_csp_case_lowest();

_csp_transfer_lowest();

_csp_main_lowest();

_csp_customerInterfaces_lowest();]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>