<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.3">
  <POU Name="_csp_case_topRail_low" Id="{de842883-2a31-49a0-b2ab-8dc54de5350c}" SpecialFunc="None">
    <Declaration><![CDATA[(*********************************** G.D S.p.A. - Technical Department ***********************************
============= PROGRAM INFO ============
FOLDER:             TBD
MACHINES INVOLVED:  TBD 

============= DESCRIPTION =============
csp main interface program

============= REVISIONS ===============
Date		Version	 	Author      	Description             
----------	-------		------------  	--------------------------------------------
2019/09/27 	0000.00	 	M.Grasso		Creation of the PRG

**********************************************************************************************************)
PROGRAM _csp_case_topRail_low
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[(* CASE *)
	(* TOP RAIL *)
		(* ACC-U-CHANGE *)
			(* LS *)
			csp_case_tr_accU_ls();
			csp_case_tr_accU_ls_width();
			(* OS *)
			csp_case_tr_accU_Os();
			csp_case_tr_accU_Os_width();
			(* DEPTH *)
			csp_case_tr_accU_depth();
			(* VIRTUAL MASTER *)
			csp_case_tr_accU_virtualMaster();
			
		(* SQUARING *)
			(* LS *)
			csp_case_tr_squaring_ls();
			csp_case_tr_squaring_ls_leading();
			csp_case_tr_squaring_ls_trailing();
			(* OS *)
			csp_case_tr_squaring_os();
			csp_case_tr_squaring_os_leading();
			csp_case_tr_squaring_os_trailing();]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>