<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.12">
  <POU Name="_csp_case_openFlap_normal" Id="{a1fe8388-ab76-449b-8356-c88f00bc9f24}" SpecialFunc="None">
    <Declaration><![CDATA[(*********************************** G.D S.p.A. - Technical Department ***********************************
============= PROGRAM INFO ============
FOLDER:             TBD
MACHINES INVOLVED:  TBD 

============= DESCRIPTION =============
csp main interface program

============= REVISIONS ===============
Date		Version	 	Author      	Description             
----------	-------		------------  	--------------------------------------------
2019/09/27 	0000.00	 	M.Grasso		Creation of the PRG

**********************************************************************************************************)
PROGRAM _csp_case_openFlap_normal
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[csp_case_openFlap_sensors();]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>