<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.3">
  <POU Name="_normal" Id="{31d40629-2f1d-4b58-8524-8c5c18f3d516}" SpecialFunc="None">
    <Declaration><![CDATA[(*********************************** G.D S.p.A. - Technical Department ***********************************
============= PROGRAM INFO ============
FOLDER:             TBD
MACHINES INVOLVED:  TBD 

============= DESCRIPTION =============
Highest task

============= REVISIONS ===============
Date		Version	 	Author      	Description             
----------	-------		------------  	--------------------------------------------
2019/04/05 	0000.00	 	G.Cera 			Creation of the PRG

**********************************************************************************************************)
{attribute 'TcCallAfterOutputUpdate'}
PROGRAM _normal
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[(* APPLICATION *)
framework_normaltask_begin();
application_status_manager();
application_status_manager_normal();

_csp_normal();

//dbg_normal();

framework_normaltask_end();]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>