<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.3">
  <POU Name="_csp_case_loader_normal" Id="{c928abf6-1305-43f1-bf4f-7fd8488cebd6}" SpecialFunc="None">
    <Declaration><![CDATA[(*********************************** G.D S.p.A. - Technical Department ***********************************
============= PROGRAM INFO ============
FOLDER:             TBD
MACHINES INVOLVED:  TBD 

============= DESCRIPTION =============
csp main interface program

============= REVISIONS ===============
Date		Version	 	Author      	Description             
----------	-------		------------  	--------------------------------------------
2019/09/27 	0000.00	 	M.Grasso		Creation of the PRG

**********************************************************************************************************)
PROGRAM _csp_case_loader_normal
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[(* CASE *)
	(* LOADER *)
		(* GUIDE *)
		csp_case_loader_guide();
		(* SENSORS *)
		csp_case_loader_sensors();
		
		
		]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>